export const defaultProducts = [
  {
    id: 'velvet-matte-01',
    name: 'Velvet Matte Lipstick',
    price: 28,
    category: 'lip',
    subcategory: 'matte',
    image: '/product_lipstick_01.jpg',
    description: 'Long-lasting matte finish with hydrating ingredients',
    isActive: true,
  },
  {
    id: 'hydrating-tint-01',
    name: 'Hydrating Lip Tint',
    price: 24,
    category: 'lip',
    subcategory: 'tint',
    image: '/product_tint_01.jpg',
    description: 'Sheer color with all-day hydration',
    isActive: true,
  },
  {
    id: 'high-shine-gloss-01',
    name: 'High-Shine Lip Gloss',
    price: 22,
    category: 'lip',
    subcategory: 'gloss',
    image: '/product_gloss_01.jpg',
    description: 'Mirror-like shine without the stickiness',
    isActive: true,
  },
  {
    id: 'satin-color-01',
    name: 'Satin Color Lipstick',
    price: 26,
    category: 'lip',
    subcategory: 'satin',
    image: '/product_lipstick_01.jpg',
    description: 'Creamy satin finish with buildable color payoff',
    isActive: true,
  },
  {
    id: 'precision-liner-01',
    name: 'Precision Lip Liner',
    price: 20,
    category: 'lip',
    subcategory: 'liner',
    image: '/product_liner_01.jpg',
    description: 'Define and shape with creamy precision',
    isActive: true,
  },
  {
    id: 'recovery-balm-01',
    name: 'Overnight Recovery Balm',
    price: 38,
    category: 'skincare',
    subcategory: 'moisturizer',
    image: '/product_balm_01.jpg',
    description: 'Wake up to renewed, radiant skin',
    isActive: true,
  },
  {
    id: 'gentle-cleanser-01',
    name: 'Gentle Milk Cleanser',
    price: 32,
    category: 'skincare',
    subcategory: 'cleanser',
    image: '/product_cleanser_01.jpg',
    description: 'Remove impurities without stripping moisture',
    isActive: true,
  },
  {
    id: 'daily-serum-01',
    name: 'Daily Glow Serum',
    price: 44,
    category: 'skincare',
    subcategory: 'serum',
    image: '/product_serum_01.jpg',
    description: 'Vitamin C brightening complex',
    isActive: true,
  },
  {
    id: 'spf-fluid-01',
    name: 'SPF 40 Mineral Fluid',
    price: 36,
    category: 'skincare',
    subcategory: 'spf',
    image: '/product_spf_01.jpg',
    description: 'Weightless protection, invisible finish',
    isActive: true,
  },
  {
    id: 'moisturizer-01',
    name: 'Hydra Boost Moisturizer',
    price: 34,
    category: 'skincare',
    subcategory: 'moisturizer',
    image: '/product_moisturizer_01.jpg',
    description: '24-hour hydration for all skin types',
    isActive: true,
  },
];
