export const defaultProducts = [
  {
    id: 'velvet-matte-01',
    name: 'Velvet Matte Lipstick',
    price: 28,
    category: 'lip',
    subcategory: 'matte',
    image: '/product_lipstick_01.jpg',
    description: 'Long-lasting matte finish with hydrating ingredients',
    isActive: true,
  },
  {
    id: 'hydrating-tint-01',
    name: 'Hydrating Lip Tint',
    price: 24,
    category: 'lip',
    subcategory: 'tint',
    image: '/product_tint_01.jpg',
    description: 'Sheer color with all-day hydration',
    isActive: true,
  },
  {
    id: 'high-shine-gloss-01',
    name: 'High-Shine Lip Gloss',
    price: 22,
    category: 'lip',
    subcategory: 'gloss',
    image: '/product_gloss_01.jpg',
    description: 'Mirror-like shine without the stickiness',
    isActive: true,
  },
  {
    id: 'satin-color-01',
    name: 'Satin Color Lipstick',
    price: 26,
    category: 'lip',
    subcategory: 'satin',
    image: '/product_lipstick_01.jpg',
    description: 'Creamy satin finish with buildable color payoff',
    isActive: true,
  },
  {
    id: 'precision-liner-01',
    name: 'Precision Lip Liner',
    price: 20,
    category: 'lip',
    subcategory: 'liner',
    image: '/product_liner_01.jpg',
    description: 'Define and shape with creamy precision',
    isActive: true,
  },
  {
    id: 'cloud-mousse-01',
    name: 'Cloud Mousse Lip Color',
    price: 30,
    category: 'lip',
    subcategory: 'matte',
    image: '/product_lipstick_01.jpg',
    description: 'Soft-focus matte color with a blurred velvet finish',
    isActive: true,
  },
  {
    id: 'vinyl-stain-01',
    name: 'Vinyl Lip Stain',
    price: 25,
    category: 'lip',
    subcategory: 'tint',
    image: '/product_tint_01.jpg',
    description: 'Weightless stain that keeps a glossy look for hours',
    isActive: true,
  },
  {
    id: 'plush-creme-01',
    name: 'Plush Creme Lipstick',
    price: 29,
    category: 'lip',
    subcategory: 'satin',
    image: '/product_lipstick_01.jpg',
    description: 'Rich satin payoff with a smooth comfortable glide',
    isActive: true,
  },
  {
    id: 'mirror-glaze-01',
    name: 'Mirror Glaze Lip Gloss',
    price: 23,
    category: 'lip',
    subcategory: 'gloss',
    image: '/product_gloss_01.jpg',
    description: 'Glass-shine gloss with cushion texture and no tack',
    isActive: true,
  },
  {
    id: 'peptide-lip-mask-01',
    name: 'Peptide Lip Mask',
    price: 27,
    category: 'lip',
    subcategory: 'balm',
    image: '/product_balm_01.jpg',
    description: 'Conditioning overnight lip treatment with peptide care',
    isActive: true,
  },
  {
    id: 'recovery-balm-01',
    name: 'Overnight Recovery Balm',
    price: 38,
    category: 'skincare',
    subcategory: 'moisturizer',
    image: '/product_balm_01.jpg',
    description: 'Wake up to renewed, radiant skin',
    isActive: true,
  },
  {
    id: 'gentle-cleanser-01',
    name: 'Gentle Milk Cleanser',
    price: 32,
    category: 'skincare',
    subcategory: 'cleanser',
    image: '/product_cleanser_01.jpg',
    description: 'Remove impurities without stripping moisture',
    isActive: true,
  },
  {
    id: 'daily-serum-01',
    name: 'Daily Glow Serum',
    price: 44,
    category: 'skincare',
    subcategory: 'serum',
    image: '/product_serum_01.jpg',
    description: 'Vitamin C brightening complex',
    isActive: true,
  },
  {
    id: 'spf-fluid-01',
    name: 'SPF 40 Mineral Fluid',
    price: 36,
    category: 'skincare',
    subcategory: 'spf',
    image: '/product_spf_01.jpg',
    description: 'Weightless protection, invisible finish',
    isActive: true,
  },
  {
    id: 'moisturizer-01',
    name: 'Hydra Boost Moisturizer',
    price: 34,
    category: 'skincare',
    subcategory: 'moisturizer',
    image: '/product_moisturizer_01.jpg',
    description: '24-hour hydration for all skin types',
    isActive: true,
  },
  {
    id: 'night-renew-serum-02',
    name: 'Night Renew Serum',
    price: 48,
    category: 'skincare',
    subcategory: 'serum',
    image: '/product_serum_01.jpg',
    description: 'Retinol alternative blend that smooths and refines overnight',
    isActive: true,
  },
  {
    id: 'barrier-cream-02',
    name: 'Barrier Rescue Cream',
    price: 39,
    category: 'skincare',
    subcategory: 'moisturizer',
    image: '/product_moisturizer_01.jpg',
    description: 'Ceramide-rich cream that supports skin barrier strength',
    isActive: true,
  },
  {
    id: 'clarity-cleanser-02',
    name: 'Clarity Gel Cleanser',
    price: 31,
    category: 'skincare',
    subcategory: 'cleanser',
    image: '/product_cleanser_01.jpg',
    description: 'Low-foam cleanser that removes buildup while staying gentle',
    isActive: true,
  },
  {
    id: 'dew-shield-spf-02',
    name: 'Dew Shield SPF 50',
    price: 38,
    category: 'skincare',
    subcategory: 'spf',
    image: '/product_spf_01.jpg',
    description: 'Daily broad-spectrum protection with a dewy skin finish',
    isActive: true,
  },
];
